#!/bin/bash

# Variables
LOCAL_REPO="/srv/samba/ezz_201911352"  # Path to local shared repository
LOG_FILE="/var/log/samba_backup.log"  # Path to log file

# Function to log messages with timestamp
log_message() {
    echo "$(date +'%Y-%m-%d %H:%M:%S') $1" >> "$LOG_FILE"
}

# Function to perform backup
perform_backup() {
    source githubs
	echo "the files have been uploded to github "


    # Check backup status and log the result
    if [ $? -eq 0 ]; then
        log_message "Backup successfully completed."
    else
        log_message "Backup failed."
    fi
}

# Main script execution

# Log file header
echo "******** Samba Backup Log ********" >> "$LOG_FILE"
log_message "Backup script started."

# Watch for file system events and trigger backup on changes
inotifywait -m -r -e create,modify,delete "$LOCAL_REPO" | while read -r directory events filename; do
   
    log_message "Change detected: $events $directory$filename"
        perform_backup
    

done
